# Build and publish extension to Marketplace

trigger:
  branches:
    include:
      - main

steps:
  - checkout: self
    fetchDepth: 0

  - task: NodeTool@0
    displayName: "NodeTool"
    inputs:
      versionSpec: "16.x"

  - task: Npm@1
    displayName: "Npm: Install"
    inputs:
      command: ci
      workingDir: extension

  - script: |
      npx nbgv cloud --all-vars
    displayName: "Script: Set version"
    workingDirectory: extension

  - script: printenv
    displayName: "Script: printenv"

  - pwsh: |
      $config = (Get-Content vss-extension.json) | ConvertFrom-Json
      $config.version = $env:NBGV_NPMPACKAGEVERSION
      $config | ConvertTo-Json -depth 3 | Set-Content vss-extension.json
    displayName: "PowerShell: Patch version"
    workingDirectory: extension

  - script: npm run package
    displayName: "Script: Package"
    workingDirectory: extension

  - script: |
      npx tfx extension publish --token $(MARKETPLACE_TOKEN) --manifest-globs vss-extension.json --overrides-file configs/release.json --output-path out
    displayName: 'Script: Publish to Marketplace'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    workingDirectory: extension
