
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: dev

    jobs:
      - deployment: dev
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploy to Dev"
                - script: sleep 10
      
  - stage: test
    jobs:
      - deployment: test
        environment: Test
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploy to Test"
                - script: sleep 10

  - stage: prod
    jobs:
      - deployment: prod
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploy to Prod"

